---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: debian11
    image: docker.io/library/python:bullseye
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
